### PR TITLE
Article related to release of 0_8_0. 

### PR DESCRIPTION
**Pull request by heistermann**

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
Looking good to me @heistermann, you can merge this into the landing page now. wradlib/wradlib#27 is ready and will be closed in a minute.

**Comment by heistermann** [comment]
How does the deployment work with the landing-page? I assume travis should trigger Pelican to build the pages, right? But I cannot find how it's done. At least the article does not appear on wradlib.github.io.

**Comment by kmuehlbauer** [comment]
@heistermann , the articel is there, but in the draft folder. You set the time to 14:00, and the system doesn't publish future artcles. Instead it has them in the drafts folder.

You can change the time (and I do not know, on what timezone they rely) within the article. No need for a new pr just do it here directly.

**Comment by heistermann** [comment]
Wow, I see...so time _does_ matter...thanks!

**Pull request merged**
